### ISSUE TITLE
Example for how to configure for multiple redis ports/instances on a single host

### ISSUE THREAD

**Issue by nanobeep** [newrelic/nri-redis#105]
## Is your feature request related to a problem? Please describe.

It's unclear how to configure the newrelic redis integration for multiple redis ports/instances on a single host.

## Feature Description

An example of how to configure the integration for multiple redis ports.

## Describe Alternatives

I've looked through all the relevant documentation, examples, etc and have also tried several guesses at how to configure this, but so far no luck at getting it to work with multiple redis ports.

## Priority

Blocker - I'm only able to use newrelic to monitor one redis instance per host, but I have 10+ redis instances per host.

**Comment by nanobeep** [comment]
Support for this feature appears to exist, just no documentation on how to use it: https://github.com/newrelic/nri-redis/issues/11

**Comment by carlossscastro** [comment]
Hi @nanobeep,

Thanks for your request.
We have reviewed it and we'll be working on adding examples for multi instance configuration.

We will send you another update here once the documentation is ready.

**Comment by carlossscastro** [comment]
https://github.com/newrelic/docs-website/pull/2797

**Comment by carlossscastro** [comment]
Hi @nanobeep ,

We have added a callout in our Redis documentation linking to our configuration files examples which now includes a multi instance example.
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/#config

Thanks again for raising this!

**Comment by nanobeep** [comment]
Super, thanks! I've implemented this and it works for 2 redis instances of my 8 (same thing on my failover host). Only 2 show up in NewRelic. So, it definitely works for 2 at a time per host, just not sure why the other 6 don't show in NewRelic. Any ideas? I've verified they are all running (all actively used production instances)

**Comment by nanobeep** [comment]
If it helps, this is my config (no sensitive details). I'm using jinja2 to loop and generate the config, so all the blocks will be identical except for the name and port:

```
integration_name: com.newrelic.redis

{% for redis_instance in redis_instances_production -%}
instances:
  - name: redis-metrics-{{ redis_instance.name }}
    command: metrics
    arguments:
      hostname: localhost
      port: {{ redis_instance.port }}
      keys:
      password:
      config_inventory: true
      keys_limit: 30

      # New users should leave this property as `true`, to identify the
      # monitored entities as `remote`. Setting this property to `false` (the
      # default value) is deprecated and will be removed soon, disallowing
      # entities that are identified as `local`.
      # Please check the documentation to get more information about local
      # versus remote entities:
      # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
      remote_monitoring: true

      # New users should leave this property as `true`, to uniquely identify the monitored entities when using
      # Unix sockets.
      use_unix_socket: true

  - name: redis-inventory-{{ redis_instance.name }}
    command: inventory
    arguments:
      hostname: localhost
      port: {{ redis_instance.port }}
      password:

      # New users should leave this property as `true`, to identify the
      # monitored entities as `remote`. Setting this property to `false` (the
      # default value) is deprecated and will be removed soon, disallowing
      # entities that are identified as `local`.
      # Please check the documentation to get more information about local
      # versus remote entities:
      # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
      remote_monitoring: true

      # New users should leave this property as `true`, to uniquely identify the monitored entities when using
      # Unix sockets.
      use_unix_socket: true
{% endfor %}
```

And here's the data structure for the loop:
```
redis_instances_production:
  - { name: 'platform-production-persist',        port: '6379' }
  - { name: 'platform-production-cache',          port: '6380' }
  - { name: 'platform-production-jobs',           port: '6381' }
  - { name: 'platform-production-performances-1', port: '6382' }
  - { name: 'platform-production-performances-2', port: '6383' }
  - { name: 'platform-production-performances-3', port: '6384' }
  - { name: 'platform-production-performances-4', port: '6385' }
  - { name: 'platform-perf-calc',                 port: '6386' }`
 ```
